# Generated by Django 5.0.6 on 2024-10-28 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='regular_price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='solde_price',
            field=models.FloatField(),
        ),
    ]
