# Generated by Django 5.0.6 on 2024-11-28 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='carrier_price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_cost',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_cost_ttc',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='taxe',
            field=models.FloatField(),
        ),
    ]
