# Generated by Django 5.0.6 on 2024-10-29 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_setting'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='email',
            field=models.EmailField(default=False, max_length=254),
            preserve_default=False,
        ),
    ]
