# Generated by Django 5.0.6 on 2024-10-30 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_page_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Navcollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('description', models.CharField(max_length=120)),
                ('button_text', models.CharField(max_length=60)),
                ('button_link', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='nav_collections')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
