# Generated by Django 5.0.6 on 2024-11-04 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_navcollection'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('description', models.CharField(max_length=120)),
                ('details', models.TextField()),
                ('price', models.FloatField()),
                ('image', models.ImageField(upload_to='carrier_images')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Transporteur',
                'verbose_name_plural': 'Transporteurs',
            },
        ),
    ]
